language: python
  - "3.8"

install:
  - pip install -r requirements.txt
  - docker build -t test2
 
script:
  - docker ps | grep -q tests/test2
  - pytest --allure-dir="./" --username= --password= --to= --subject= --body=

services:
  - docker